POST https://3333-henrique998-emailn-jko5ydl6d4i.ws-us107.gitpod.io/campaigns

{
  "name": "cam",
  "content": "campaign 03 description",
  "emails": ["jhondoe@gmail.com", "henrique@gmail.com"]
}

###

GET https://3333-henrique998-emailn-jko5ydl6d4i.ws-us107.gitpod.io/campaigns